<think>
No reasoning found</think>
Here is the code snippet with the unresolved conflict:

```java
import java.io.IOException;
import java.util.Iterator;

import org.apache.pig.PigException;
import org.apache.pig.backend.executionengine.ExecException;
<<<<<<< HEAD
import org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.LitePackager;
=======
import org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.Packager;
>>>>>>> 88ae4a5fc1d6ff4a9d3c070fe2fc64a50827c37a
import org.apache.pig.impl.io.NullableTuple;
import org.apache.pig.impl.io.PigNullableWritable;

/**
<<<<<<< HEAD

```